services:
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
            - "15692:15692"
        environment:
            - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
            - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq
        networks:
            - microservices_network
        healthcheck:
            test: ["CMD", "rabbitmqctl", "status"]
            interval: 10s
            timeout: 5s
            retries: 5
        command: >
            bash -c "
                rabbitmq-plugins enable rabbitmq_prometheus;
                rabbitmq-server
            "

    postgres-auth-master:
        image: postgres:16
        container_name: postgres-auth-master
        ports:
            - "5433:5432"
        environment:
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=postgres
            - REPLICATOR_PASSWORD=replicator123
        volumes:
            - postgres_auth_data:/var/lib/postgresql/data
            - postgres_auth_archive:/var/lib/postgresql/archive
            - ./postgres-auth-master/postgresql.conf:/etc/postgresql/postgresql.conf
            - ./postgres-auth-master/pg_hba.conf:/etc/postgresql/pg_hba.conf
            - ./postgres-auth-master/init-auth-master.sh:/docker-entrypoint-initdb.d/init-auth-master.sh
        command: postgres -c config_file=/etc/postgresql/postgresql.conf -c hba_file=/etc/postgresql/pg_hba.conf
        networks:
            - microservices_network
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5

    postgres-shortener-master:
        image: postgres:16
        container_name: postgres-shortener-master
        ports:
            - "5434:5432"
        environment:
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=postgres
            - REPLICATOR_PASSWORD=replicator123
        volumes:
            - postgres_shortener_master_data:/var/lib/postgresql/data
            - postgres_shortener_archive:/var/lib/postgresql/archive
            - ./postgres-shortener-master/postgresql.conf:/etc/postgresql/postgresql.conf
            - ./postgres-shortener-master/pg_hba.conf:/etc/postgresql/pg_hba.conf
            - ./postgres-shortener-master/init-shortener-master.sh:/docker-entrypoint-initdb.d/init-shortener-master.sh
        command: postgres -c config_file=/etc/postgresql/postgresql.conf -c hba_file=/etc/postgresql/pg_hba.conf
        networks:
            - microservices_network
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5

    postgres-shortener-slave1:
        image: postgres:16
        container_name: postgres-shortener-slave1
        ports:
            - "5435:5432"
        environment:
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=postgres
            - REPLICATOR_PASSWORD=replicator123
            - PGUSER=${DB_USERNAME}
        volumes:
            - postgres_shortener_slave1_data:/var/lib/postgresql/data
            - ./postgres-shortener-slave/postgresql.conf:/etc/postgresql/postgresql.conf
            - ./postgres-shortener-slave/pg_hba.conf:/etc/postgresql/pg_hba.conf
            - ./postgres-shortener-slave/setup-slave.sh:/docker-entrypoint-initdb.d/setup-slave.sh
        entrypoint: ["/docker-entrypoint-initdb.d/setup-slave.sh"]
        user: root
        depends_on:
            postgres-shortener-master:
                condition: service_healthy
        networks:
            - microservices_network
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 15s
            timeout: 10s
            retries: 10
            start_period: 60s

    postgres-shortener-slave2:
        image: postgres:16
        container_name: postgres-shortener-slave2
        ports:
            - "5436:5432"
        environment:
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=postgres
            - REPLICATOR_PASSWORD=replicator123
            - PGUSER=${DB_USERNAME}
        volumes:
            - postgres_shortener_slave2_data:/var/lib/postgresql/data
            - ./postgres-shortener-slave/postgresql.conf:/etc/postgresql/postgresql.conf
            - ./postgres-shortener-slave/pg_hba.conf:/etc/postgresql/pg_hba.conf
            - ./postgres-shortener-slave/setup-slave.sh:/docker-entrypoint-initdb.d/setup-slave.sh
        entrypoint: ["/docker-entrypoint-initdb.d/setup-slave.sh"]
        user: root
        depends_on:
            postgres-shortener-master:
                condition: service_healthy
        networks:
            - microservices_network
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 15s
            timeout: 10s
            retries: 10
            start_period: 60s

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        depends_on:
            - postgres-auth-master
            - postgres-shortener-master
        ports:
            - "5050:80"
        environment:
            - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
            - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
        volumes:
            - pgadmin_data:/var/lib/pgadmin
        networks:
            - microservices_network

    pgbouncer:
        image: edoburu/pgbouncer
        container_name: pgbouncer
        ports:
            - "6432:6432"
        environment:
            DB_USER: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./pgbouncer/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini
            - ./pgbouncer/userlist.txt:/etc/pgbouncer/userlist.txt
        depends_on:
            - postgres-auth-master
            - postgres-shortener-master
            - postgres-shortener-slave1
            - postgres-shortener-slave2
        networks:
            - microservices_network

    redis:
        image: redis:7
        container_name: redis
        ports:
            # - "6379:6379"
            - "15642:6379"
        networks:
            - microservices_network

    auth-service:
        build:
            context: .
            dockerfile: apps/auth-service/Dockerfile
        container_name: auth-service
        env_file:
            - .env
        ports:
            - "3001:3001"
        depends_on:
            - postgres-auth-master
            - rabbitmq
        networks:
            - microservices_network
        restart: unless-stopped
        command: sh -c "
            until nc -z postgres-auth-master 5432; do
            echo 'Waiting for Auth Postgres...';
            sleep 2;
            done;
            until nc -z rabbitmq 5672; do
            echo 'Waiting for RabbitMQ...';
            sleep 2;
            done;
            node dist/apps/auth-service/main
            "

    url-shortener:
        build:
            context: .
            dockerfile: apps/url-shortener/Dockerfile
        container_name: url-shortener
        env_file:
            - .env
        ports:
            - "3002:3002"
        depends_on:
            - postgres-shortener-master
            - postgres-shortener-slave1
            - postgres-shortener-slave2
            - rabbitmq
            - redis
        networks:
            - microservices_network
        restart: unless-stopped
        command: sh -c "
            until nc -z postgres-shortener-master 5432; do
            echo 'Waiting for URL Shortener Master Postgres...';
            sleep 2;
            done;
            until nc -z postgres-shortener-slave1 5432; do
            echo 'Waiting for URL Shortener Slave1 Postgres...';
            sleep 2;
            done;
            until nc -z postgres-shortener-slave2 5432; do
            echo 'Waiting for URL Shortener Slave2 Postgres...';
            sleep 2;
            done;
            until nc -z rabbitmq 5672; do
            echo 'Waiting for RabbitMQ...';
            sleep 2;
            done;
            node dist/apps/url-shortener/main
            "

    api-gateway:
        build:
            context: .
            dockerfile: apps/api-gateway/Dockerfile
        container_name: api-gateway
        env_file:
            - .env
        ports:
            - "2000:2000"
        depends_on:
            - auth-service
            - url-shortener
        networks:
            - microservices_network
        restart: unless-stopped
        command: sh -c "
            until nc -z postgres-auth-master 5432; do
            echo 'Waiting for Auth Postgres...';
            sleep 2;
            done;
            until nc -z postgres-shortener-master 5432; do
            echo 'Waiting for URL Shortener Postgres...';
            sleep 2;
            done;
            until nc -z rabbitmq 5672; do
            echo 'Waiting for RabbitMQ...';
            sleep 2;
            done;
            node dist/apps/api-gateway/main
            "

    prometheus:
        image: prom/prometheus:v2.47.0
        container_name: prometheus
        ports:
            - "9090:9090"
        volumes:
            - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
            - prometheus_data:/prometheus
        command:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
            - "--web.console.libraries=/etc/prometheus/console_libraries"
            - "--web.console.templates=/etc/prometheus/consoles"
            - "--storage.tsdb.retention.time=200h"
            - "--web.enable-lifecycle"
        networks:
            - microservices_network
        restart: unless-stopped

    grafana:
        image: grafana/grafana:10.1.0
        container_name: grafana
        ports:
            - "3000:3000"
        volumes:
            - grafana_data:/var/lib/grafana
            - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
            - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
        environment:
            - GF_SECURITY_ADMIN_USER=admin
            - GF_SECURITY_ADMIN_PASSWORD=admin
            - GF_USERS_ALLOW_SIGN_UP=false
        networks:
            - microservices_network
        restart: unless-stopped
        depends_on:
            - prometheus

    postgres-exporter-auth:
        image: prometheuscommunity/postgres-exporter:v0.13.2
        container_name: postgres-exporter-auth
        ports:
            - "9187:9187"
        environment:
            DATA_SOURCE_NAME: "postgresql://${DB_USERNAME}:${DB_PASSWORD}@postgres-auth-master:5432/auth_service?sslmode=disable"
        depends_on:
            - postgres-auth-master
        networks:
            - microservices_network
        restart: unless-stopped

    postgres-exporter-shortener:
        image: prometheuscommunity/postgres-exporter:v0.13.2
        container_name: postgres-exporter-shortener
        ports:
            - "9188:9188"
        environment:
            DATA_SOURCE_NAME: "postgresql://${DB_USERNAME}:${DB_PASSWORD}@postgres-shortener-master:5432/url_shortener?sslmode=disable"
        command: ["--web.listen-address=:9188"]
        depends_on:
            - postgres-shortener-master
        networks:
            - microservices_network
        restart: unless-stopped

    redis-exporter:
        image: oliver006/redis_exporter:v1.45.0
        container_name: redis-exporter
        ports:
            - "9121:9121"
        environment:
            REDIS_ADDR: "redis://redis:6379"
        depends_on:
            - redis
        networks:
            - microservices_network
        restart: unless-stopped

    node-exporter:
        image: prom/node-exporter:v1.6.1
        container_name: node-exporter
        ports:
            - "9100:9100"
        volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /:/rootfs:ro
        command:
            - "--path.procfs=/host/proc"
            - "--path.sysfs=/host/sys"
            - "--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)"
        networks:
            - microservices_network
        restart: unless-stopped

volumes:
    postgres_auth_data:
    postgres_auth_archive:
    postgres_shortener_master_data:
    postgres_shortener_slave1_data:
    postgres_shortener_slave2_data:
    postgres_shortener_archive:
    rabbitmq_data:
    pgadmin_data:
    prometheus_data:
    grafana_data:

networks:
    microservices_network:
        driver: bridge
