global:
    scrape_interval: 15s
    evaluation_interval: 15s

rule_files:

scrape_configs:
    - job_name: "prometheus"
      static_configs:
          - targets: ["localhost:9090"]

    - job_name: "api-gateway"
      static_configs:
          - targets: ["api-gateway:2000"]
      metrics_path: "/metrics"
      scrape_interval: 5s

    - job_name: "auth-service"
      static_configs:
          - targets: ["auth-service:3001"]
      metrics_path: "/metrics"
      scrape_interval: 5s

    - job_name: "url-shortener"
      static_configs:
          - targets: ["url-shortener:3002"]
      metrics_path: "/metrics"
      scrape_interval: 5s

    - job_name: "postgres-auth"
      static_configs:
          - targets: ["postgres-exporter-auth:9187"]
      metrics_path: "/metrics"
      scrape_interval: 10s

    - job_name: "postgres-shortener"
      static_configs:
          - targets: ["postgres-exporter-shortener:9188"]
      metrics_path: "/metrics"
      scrape_interval: 10s

    - job_name: "redis"
      static_configs:
          - targets: ["redis-exporter:9121"]
      metrics_path: "/metrics"
      scrape_interval: 10s

    - job_name: "rabbitmq"
      static_configs:
          - targets: ["rabbitmq:15692"]
      metrics_path: "/metrics"
      scrape_interval: 10s

    - job_name: "node-exporter"
      static_configs:
          - targets: ["node-exporter:9100"]
      metrics_path: "/metrics"
      scrape_interval: 10s
